TELEGRAM:
    chat_id: 
    token: 
    disable_notification: False

GENERAL:
    check_delay: 300

PRODUCTS:
    [
        {
            name: fist product,
            price: 400
        },
        {
            name: second product,
            price: 500
        }       
    ]